# Generated by Django 5.2.7 on 2026-01-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default_profile_pic_modb9y.svg', null=True, upload_to='profile_pictures/'),
        ),
    ]
