# Generated by Django 5.2.7 on 2026-01-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='https://res.cloudinary.com/dld9ikquj/image/upload/v1768036307/default_profile_pic_modb9y.svg', upload_to='posts/'),
            preserve_default=False,
        ),
    ]
