# Generated by Django 5.2.7 on 2026-02-01 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.URLField(default='https://res.cloudinary.com/dld9ikquj/image/upload/v1768036307/default_profile_pic_modb9y.svg'),
        ),
    ]
